### ISSUE TITLE
Add to Extention Store

### ISSUE THREAD

**Issue by raycekar** [AMeng/personal_capital_plus#13]
I like the app, would it be possible to get it added to both the firefox/chrome extension store?

**Comment by AMeng** [comment]
Hey, @raycekar. The extension is already available on the Chrome Web Store [here](https://chromewebstore.google.com/detail/personal-capital-plus/bkaagconbehchjkhgkojhabaklbpfcfa). This is documented in the README as the suggested way to install it.

I haven't tested the extension in Firefox, so I'm not sure if it would work. There are a few explicit `chrome` function calls (like [this one](https://github.com/AMeng/personal_capital_plus/blob/9820c6c29721ce9fb0c875b67b31d307a8ffdda7/options.js#L13)) that probably need to be updated to support both platforms. If you're able to get this working in Firefox, I'd be happy to upload it to their store as well.

**Comment by raycekar** [comment]
Hey @AMeng, i apologize as i must had overlooked that part in the read me.

**Comment by jiexi** [comment]
I may try to work on this in the coming weeks if I can commit to finally switching away from Chrome. No promises

**Comment by AMeng** [comment]
@calvinpark option 4 sounds best to me assuming there aren't a ton of differences between the two code paths. My assumption is that there are generic replacements for all the chrome-specific stuff that will work for both (though I haven't really looked into it). And I'm happy to continue supporting and testing against both browsers going forward if you can get it working. Feel free to open a pull request and I'll take a look.

**Comment by calvinpark** [comment]
Sounds good, thanks for the clear answer. I'm new to this but I'll start digging.

**Comment by calvinpark** [comment]
Any progress?

**Comment by AMeng** [comment]
The add-on has been submitted and is pending approval from Mozilla.

**Comment by calvinpark** [comment]
I see it! https://addons.mozilla.org/en-US/firefox/addon/personal-capital-plus/

For some reason it's working only intermittently :(  I'll try to debug.

**Comment by AMeng** [comment]
I'm not able to find any issues from my testing with Firefox. What's the issue you're seeing?

Maybe check that you're not still running a development version from your prior testing? And do a hard refresh?

**Comment by calvinpark** [comment]
Cmd + shift + R always applies the changes by the extension, but cmd + R applies it only once every 5 times or so.

Not a big deal since I know how to apply the change, but I worry that the extension will receive bad reviews. Are you always seeing the changes applied on every refresh, with or without shift?

**Comment by AMeng** [comment]
Ah, I can recreate it on occasion if I refresh fairly quickly. Some things I noticed:

1. No errors in the console.
2. The options link in the dropdown always gets added, even when the styles don't. That style change happens outside the observer.

My guess would be a race condition or an issue with reading the options from local storage. Feel free to debug if its of interest to you. I'm not worried about bad reviews 😄

**Comment by calvinpark** [comment]
Yup it's definitely a race. Maybe a message in the "About this extension" section that sometimes "Ctrl+Shift+R" or "Cmd+Shift+R" is needed would help?

**Comment by AMeng** [comment]
I just uploaded version 3.2 that should fix the race condition in Firefox. Or at least, I can't recreate it anymore 😄 

This was the fix: https://github.com/AMeng/personal_capital_plus/blob/38ada9f6d8055004c15fdf36da6bf8e3093ee10c/manifest.json#L11

**Comment by calvinpark** [comment]
That was it, bravo!
